### ISSUE TITLE
Reason not to use Selenium.Support

### ISSUE THREAD

**Issue by gregpakes** [ObjectivityLtd/Test.Automation#31]
I was wondering if there is a reason why the framework accesses elements like this:

```
private readonly ElementLocator
            linkLocator = new ElementLocator(Locator.CssSelector, "a[href='/{0}']"),
            basicAuthLink = new ElementLocator(Locator.XPath, "//a[contains(text(),'Auth')]");
```
rather than the Selenium.Support method:

```
    [FindsBy(How = How.Id, Using = "Username")]
    private IWebElement _username;

    [FindsBy(How = How.Id, Using = "Password")]
    private IWebElement _password;

    [FindsBy(How = How.Id, Using = "login-button")]
    private IWebElement _loginbutton;
```

I'm curious whether this is a conscious design decision.  If so, why?

**Comment by MysteryAchievement** [comment]
I'd like to know the answer to this too.  Does anything in the framework prevent using  the Selenium.Support method?

**Comment by raczeja** [comment]
We just decided to not use Page Factory in our framework,
you can find plenty of discussions why to use them or why not to use them, 
e.g. http://iainrose.tumblr.com/post/27612544255/closing-the-pagefactory

In our solution locators can be parameterized e.g. `"//*[@title='{0}' and @ms.title='{1}']"`  by using Format method.

Example how to use it:
```csharp
private readonly ElementLocator fileLink = new ElementLocator(Locator.CssSelector, "a[href='download/{0}']");
...
this.Driver.GetElement(this.fileLink.Format("first_file.txt")).Click();
this.Driver.GetElement(this.fileLink.Format("second_file.txt")).Click();
```

You can still use Page Factory in our framework 
```csharp
[FindsBy(How = How.Id, Using = "username")]
public IWebElement userName { get; set; }
this.userName.SendKeys(BaseConfiguration.Username);
```

but it doesn't make sense, because you will not be able to use e.g. methods like GetElement from [SearchContextExtensions](https://objectivityltd.github.io/Test.Automation/html/6b3a28a9-75c6-bda7-e44e-962f1e91c477.htm) class or [parameterize](https://github.com/ObjectivityLtd/Test.Automation/wiki/More%20common%20locators) locators .
