### ISSUE TITLE
More flexibility around Browser Capabilities

### ISSUE THREAD

**Issue by gregpakes** [ObjectivityLtd/Test.Automation#43]
My scenario requires that I have more control around setting browser capabilities.  I have created a branch which creates a new event on the DriverContext that allows me to hook into the pipeline to add more capabilities at runtime.

The branch is here: https://github.com/gregpakes/Test.Automation/tree/custom-capabilities

I haven't created a PR as it contains checkins from other branches I have submitted PRs for.

Please let me know if this is of interest to you and how I should go about submitting a PR.

**Comment by raczeja** [comment]
these changes are ok for us, please create PR to 3.0.6. branch, I will solve the conflicts during merge. Before creating PR please run code analysis in Visual Studio and solve any warning from your commits (menu Analyze-Run Code Analysis) otherwise build can failed on our site.  
Please also describe shortly how to use your functionality, I will added that description on wiki.
thanks @gregpakes  for you contribution.

**Comment by gregpakes** [comment]
Done #45

**Comment by raczeja** [comment]
Merged, please just write an example how to used for a wiki.

**Comment by gregpakes** [comment]
Done - short and simple, but hopefully enough to illustrate the feature.
